name: libportal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure libportal
      run: meson setup --prefix=/usr _build
    - name: Build libportal
      run: ninja -C_build
